# Generated by Django 4.2.2 on 2023-07-01 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('fantasy', 'Fantasy')], max_length=20)),
                ('publication_year', models.IntegerField()),
                ('refid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
